import type { SwimSession, SwimWorkout, SwimWorkoutSet } from "../types";

export const swimWorkouts: SwimWorkout[] = [
  { id: 2, remoteId: "w2", name: "Workout 2", note: "", setCount: 3, userId: "user-1" },
  { id: 4, remoteId: "w4", name: "Workout 4", note: "", setCount: 1, userId: "user-1" },
];

export const swimSets: SwimWorkoutSet[] = [
  {
    id: 1,
    remoteId: "set-1",
    workoutId: 2,
    distance: "100",
    description: "kick with board, snorkel",
    splitTotal: "",
    equipment: "100",
    fins: "",
    sortOrder: 0,
  },
  {
    id: 2,
    remoteId: "set-2",
    workoutId: 2,
    distance: "100",
    description: "kick streamline",
    splitTotal: "",
    equipment: "",
    fins: "",
    sortOrder: 1,
  },
  {
    id: 3,
    remoteId: "set-3",
    workoutId: 2,
    distance: "300",
    description: "fly drill",
    splitTotal: "500",
    equipment: "",
    fins: "",
    sortOrder: 2,
  },
  {
    id: 4,
    remoteId: "set-4",
    workoutId: 4,
    distance: "200",
    description: "warm up free",
    splitTotal: "",
    equipment: "",
    fins: "",
    sortOrder: 0,
  },
  {
    id: 5,
    remoteId: "set-5",
    workoutId: 2,
    distance: "2500",
    description: "",
    splitTotal: "",
    equipment: "",
    fins: "",
    sortOrder: 3,
  },
];

export const swimSessions: SwimSession[] = [
  {
    id: 1,
    remoteId: "s1",
    date: "6/4/2025",
    meters: "2500",
    miles: "1.55",
    stroke: "",
    note: "Red Cross 15 mile - Workout 2",
    extra: "",
    workoutId: 2,
    workoutName: "Workout 2",
    userId: "user-1",
  },
  {
    id: 2,
    remoteId: "s2",
    date: "6/24/2025",
    meters: "3000",
    miles: "1.86",
    stroke: "",
    note: "Workout 4",
    extra: "",
    workoutId: 4,
    workoutName: "Workout 4",
    userId: "user-1",
  },
  {
    id: 3,
    remoteId: "s3",
    date: "6/28/2025",
    meters: "2800",
    miles: "1.74",
    stroke: "",
    note: "",
    extra: "June Redcross Goal",
    workoutId: null,
    workoutName: null,
    userId: "user-1",
  },
  {
    id: 4,
    remoteId: "s4",
    date: "6/10/2025",
    meters: "2500",
    miles: "1.55",
    stroke: "",
    note: "Workout 2",
    extra: "",
    workoutId: 2,
    workoutName: "Workout 2",
    userId: "user-1",
  },
  {
    id: 5,
    remoteId: "s5",
    date: "7/15/2025",
    meters: "3200",
    miles: "1.99",
    stroke: "",
    note: "Workout 5",
    extra: "",
    workoutId: null,
    workoutName: null,
    userId: "user-1",
  },
];

export const swimSeed = {
  swimSessions,
  swimWorkouts,
  swimSets,
};
